name: Publish to TestPyPI

on:
  push:
    branches:
      - package-test-new-structure  # Change this to your actual branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # Works on Linux (default GitHub runner)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: package-test-new-structure  # Ensure the correct branch is checked out

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*
